[package]
name = "elise-test-utils"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
elise-ast = { path = "../ir/ast" }
elise-aast = { path = "../ir/aast" }
elise-bindings = { path = "../ir/bindings" }
elise-parser = { path = "../frontend/parser" }
elise-semanalyzer = { path = "../frontend/semanalyzer" }
