/**
 * This file is an entry point for the program which also represents a program consumer.
 * We can run the program in 4 different ways:
 *      1. Plain run
 *      2. Bytecode generation
 *      3. Pre-generated bytecode execution
 *      4. Validation
 *
 * Library crate exposes all these functions and returns a descriptive errors
 * which should be handled here. Any module, that is behind the library crate, must
 * not panic or print any messages into the std out.
 *
 * This binary crate must decide how to handle these cases on its own.
 * This allows us to not be tightly coupled with environment in which our program runs.
 */
pub mod out;

use elise::conf::{Conf, ModeBuildConf, ModeExecConf, ModeRunConf, ModeValidateConf};
use elise::fsys::{read_file_bytes, read_file_string, write_file};
use elise_errors::LangErr;

use std::env;

use crate::out::msg_conf;
use crate::out::msg_csv_parser;
use crate::out::msg_csv_schema_resolver;
use crate::out::msg_fsys;
use crate::out::msg_modes;
use crate::out::msg_parser;
use crate::out::utils::{panic_hook, print_bytecode};

fn handle_lang_err(lang_err: &LangErr, source_code: &[u8], schema_source_code: &[u8]) -> ! {
    use LangErr::*;

    match lang_err {
        Parser(err) => msg_parser::print_err(err, source_code),
        CsvParser(err) => msg_csv_parser::print_err(err),
        CsvSchemaResolver(err) => msg_csv_schema_resolver::print_err(err, schema_source_code),
    }

    std::process::exit(1);
}

fn cli_run(conf: &ModeRunConf) {
    let source_code = match read_file_bytes(&conf.source_code_path) {
        Ok(desc) => desc.content,
        Err(e) => return msg_fsys::print_file_rw_err(&e.message, &e.path, true),
    };

    let schema = match read_file_bytes(&conf.data_schema_path) {
        Ok(desc) => desc.content,
        Err(e) => return msg_fsys::print_file_rw_err(&e.message, &e.path, true),
    };

    match read_file_string(&conf.data_path) {
        Ok(data_desc) => {
            let run_res = elise::run(&source_code, &data_desc.content, &schema, conf)
                .unwrap_or_else(|e| handle_lang_err(&e, &source_code, &schema));

            msg_modes::print_run_result(&run_res.output, run_res.ms);

            if run_res.config.print_bytecode {
                print_bytecode(&run_res.bytecode);
            }

            if let Some(path) = run_res.config.output_path.as_ref() {
                match write_file(path, &run_res.output) {
                    Ok(_) => msg_fsys::print_saved_to(path),
                    Err(err) => msg_fsys::print_file_rw_err(&err.message, &err.path, false),
                }
            }
        }
        Err(data_read_err) => {
            msg_fsys::print_file_rw_err(&data_read_err.message, &data_read_err.path, true)
        }
    }
}

fn cli_build(conf: &ModeBuildConf) {
    let source_code = match read_file_bytes(&conf.source_code_path) {
        Ok(desc) => desc.content,
        Err(e) => return msg_fsys::print_file_rw_err(&e.message, &e.path, true),
    };

    let schema = match read_file_bytes(&conf.data_schema_path) {
        Ok(desc) => desc.content,
        Err(e) => return msg_fsys::print_file_rw_err(&e.message, &e.path, true),
    };

    let build_res = elise::build(&source_code, &schema, conf)
        .unwrap_or_else(|e| handle_lang_err(&e, &source_code, &schema));

    let out_path = &build_res.config.executable_output_path;

    match write_file(out_path, &build_res.executale_output) {
        Ok(_) => msg_modes::print_build_result(out_path, build_res.ms),
        Err(err) => msg_fsys::print_file_rw_err(&err.message, &err.path, false),
    }
}

fn cli_exec(conf: &ModeExecConf) {
    match (
        read_file_bytes(&conf.executable_path),
        read_file_string(&conf.data_path),
    ) {
        (Ok(executable_desc), Ok(data_desc)) => {
            let exec_res = elise::exec(&executable_desc.content, &data_desc.content, conf)
                .unwrap_or_else(|e| handle_lang_err(&e, &[], &[]));

            msg_modes::print_run_result(&exec_res.output, exec_res.ms);
        }
        (Err(executable_read_err), _) => msg_fsys::print_file_rw_err(
            &executable_read_err.message,
            &executable_read_err.path,
            true,
        ),
        (_, Err(data_read_err)) => {
            msg_fsys::print_file_rw_err(&data_read_err.message, &data_read_err.path, true)
        }
    };
}

fn cli_validate(conf: &ModeValidateConf) {
    let schema = match read_file_bytes(&conf.data_schema_path) {
        Ok(desc) => desc.content,
        Err(e) => return msg_fsys::print_file_rw_err(&e.message, &e.path, true),
    };

    match read_file_string(&conf.data_path) {
        Ok(data_desc) => {
            let validate_res = elise::validate(&data_desc.content, &schema, conf)
                .unwrap_or_else(|e| handle_lang_err(&e, &[], &schema));

            msg_modes::print_validate_result(validate_res.ms);
        }
        Err(data_read_err) => {
            msg_fsys::print_file_rw_err(&data_read_err.message, &data_read_err.path, true)
        }
    };
}

fn main() {
    std::panic::set_hook(Box::new(|info| {
        panic_hook(info);
    }));

    // Skip first argument which is the name of the program.
    let args: Vec<String> = env::args().skip(1).collect();

    let config = Conf::new(&args);

    if let Err(conf_err) = config {
        return msg_conf::print_err(&conf_err);
    }

    match config.unwrap() {
        Conf::Run(run_conf) => cli_run(&run_conf),
        Conf::Build(build_conf) => cli_build(&build_conf),
        Conf::Exec(exec_conf) => cli_exec(&exec_conf),
        Conf::Validate(validate_conf) => cli_validate(&validate_conf),
    }
}
