/**
 * This file is an entry point for the program which also represents a program consumer.
 * We can run the program in 4 different ways:
 *      1. Plain run
 *      2. Bytecode generation
 *      3. Pre-generated bytecode execution
 *      4. Validation
 *
 * Library crate exposes all these functions and returns a descriptive errors
 * which should be handled here. Any module, that is behind the library crate, must
 * not panic or print any messages into the std out.
 *
 * This binary crate must decide how to handle these cases on its own.
 * This allows us to not be tightly coupled with environment in which our program runs.
 */
pub mod out;

use elise;
use elise::conf::{Conf, ConfErr, ModeBuildConf, ModeExecConf, ModeRunConf, ModeValidateConf};
use elise::fsys::{read_files, write_file};
use elise_shared::errors::LangErr;

use std::env;

fn handle_conf_err(conf_err: &ConfErr) {
    match conf_err {
        ConfErr::ExtInvalid(ext) => out::conf_err_ext_invalid(ext),
        ConfErr::ArgInvalid(arg) => out::conf_err_arg_invalid(&arg.provided, &arg.arg_name),
        ConfErr::ArgRequired(arg) => out::conf_err_arg_required(arg),
    }
}

fn handle_lang_err(lang_err: &LangErr) {
    use LangErr::*;

    match lang_err {
        ScParser(sc_parser_err) => out::sc_parser_err(sc_parser_err),
        CsvParser(csv_parser_err) => out::csv_parser_err(csv_parser_err),
    }
}

fn cli_run(conf: &ModeRunConf) {
    match read_files(&[
        &conf.source_code_path,
        &conf.data_path,
        &conf.data_schema_path,
    ]) {
        Ok(read_res) => {
            let run_res = elise::run(
                &read_res[0].content,
                &read_res[1].content,
                &read_res[2].content,
                &conf,
            );

            if let Err(run_err) = &run_res {
                return handle_lang_err(&run_err);
            }

            let run_res = run_res.unwrap();
            out::run_result(&run_res.output, run_res.ms);

            if run_res.config.print_bytecode {
                out::print_bytecode(&run_res.bytecode);
            }

            if let Some(path) = run_res.config.output_path.as_ref() {
                match write_file(path, &run_res.output) {
                    Ok(_) => out::fsys_saved_to(path),
                    Err(err) => out::fsys_file_writer_err(&err.message, path),
                }
            }
        }
        Err(read_err) => {
            out::fsys_file_reader_err(&read_err.message, &read_err.path);
        }
    };
}

fn cli_build(conf: &ModeBuildConf) {
    match read_files(&[&conf.source_code_path, &conf.data_schema_path]) {
        Ok(read_res) => {
            let build_res = elise::build(&read_res[0].content, &read_res[1].content, &conf);

            if let Err(build_err) = &build_res {
                return handle_lang_err(&build_err);
            }

            let build_res = build_res.unwrap();
            let out_path = &build_res.config.executable_output_path;

            match write_file(out_path, &build_res.executale_output) {
                Ok(_) => out::build_result(out_path, build_res.ms),
                Err(err) => out::fsys_file_writer_err(&err.message, out_path),
            }
        }
        Err(read_err) => out::fsys_file_reader_err(&read_err.message, &read_err.path),
    };
}

fn cli_exec(conf: &ModeExecConf) {
    match read_files(&[&conf.executable_path, &conf.data_path]) {
        Ok(read_res) => {
            let exec_res = elise::exec(&read_res[0].content, &read_res[1].content, &conf);

            if let Err(exec_err) = &exec_res {
                return handle_lang_err(&exec_err);
            }

            let exec_res = exec_res.unwrap();
            out::run_result(&exec_res.output, exec_res.ms);
        }
        Err(read_err) => out::fsys_file_reader_err(&read_err.message, &read_err.path),
    };
}

fn cli_validate(conf: &ModeValidateConf) {
    match read_files(&[&conf.data_path, &conf.data_schema_path]) {
        Ok(read_res) => {
            let validate_res = elise::validate(&read_res[0].content, &read_res[1].content, &conf);

            if let Err(validate_err) = &validate_res {
                return handle_lang_err(&validate_err);
            }

            let validate_res = validate_res.unwrap();
            out::validate_result(validate_res.ms);
        }
        Err(read_err) => out::fsys_file_reader_err(&read_err.message, &read_err.path),
    };
}

fn main() {
    std::panic::set_hook(Box::new(|info| {
        out::panic_hook(info);
    }));

    // Skip first argument which is the name of the program.
    let args: Vec<String> = env::args().skip(1).collect();

    let config = Conf::new(&args);

    if let Err(conf_err) = config {
        return handle_conf_err(&conf_err);
    }

    match config.unwrap() {
        Conf::Run(run_conf) => cli_run(&run_conf),
        Conf::Build(build_conf) => cli_build(&build_conf),
        Conf::Exec(exec_conf) => cli_exec(&exec_conf),
        Conf::Validate(validate_conf) => cli_validate(&validate_conf),
    }
}
